package com.studyplanner.app.ui.theme

import androidx.compose.ui.graphics.Color

data class AppColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
)

data class AppGradientScheme(
    val backgroundStart: Color,
    val backgroundMid: Color,
    val backgroundEnd: Color,
    val cardGradientStart: Color,
    val cardGradientEnd: Color,
    val primaryGradientStart: Color,
    val primaryGradientEnd: Color,
    val accentGradientStart: Color,
    val accentGradientEnd: Color,
)

data class AppTheme(
    val id: String,
    val displayName: String,
    val emoji: String,
    val isDark: Boolean,
    val colors: AppColorScheme,
    val gradients: AppGradientScheme,
)

object AppThemes {

    val OceanBlue = AppTheme(
        id = "ocean_blue",
        displayName = "Ocean Blue",
        emoji = "🌊",
        isDark = false,
        colors = AppColorScheme(
            primary = Color(0xFF1565C0),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFBBDEFB),
            onPrimaryContainer = Color(0xFF0A2F6B),
            secondary = Color(0xFFE65100),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFFE0B2),
            onSecondaryContainer = Color(0xFF7B1F00),
            tertiary = Color(0xFF43A047),
            onTertiary = Color.White,
            background = Color(0xFFFAFAFA),
            onBackground = Color(0xFF121212),
            surface = Color.White,
            onSurface = Color(0xFF121212),
            surfaceVariant = Color(0xFFF5F5F5),
            onSurfaceVariant = Color(0xFF424242),
            outline = Color(0xFFBDBDBD),
            error = Color(0xFFE53935),
            onError = Color.White,
            errorContainer = Color(0xFFFFCDD2),
            onErrorContainer = Color(0xFF7B0000),
        ),
        gradients = AppGradientScheme(
            backgroundStart = Color(0xFF0A1628),
            backgroundMid = Color(0xFF1A237E),
            backgroundEnd = Color(0xFF0D47A1),
            cardGradientStart = Color(0xFF1565C0),
            cardGradientEnd = Color(0xFF1A237E),
            primaryGradientStart = Color(0xFF1565C0),
            primaryGradientEnd = Color(0xFF0D47A1),
            accentGradientStart = Color(0xFFE65100),
            accentGradientEnd = Color(0xFF7B1F00),
        )
    )

    val MidnightDark = AppTheme(
        id = "midnight_dark",
        displayName = "Midnight",
        emoji = "🌙",
        isDark = true,
        colors = AppColorScheme(
            primary = Color(0xFF64B5F6),
            onPrimary = Color(0xFF0A2F6B),
            primaryContainer = Color(0xFF0D47A1),
            onPrimaryContainer = Color(0xFFBBDEFB),
            secondary = Color(0xFFFFB74D),
            onSecondary = Color(0xFF7B1F00),
            secondaryContainer = Color(0xFFBF360C),
            onSecondaryContainer = Color(0xFFFFE0B2),
            tertiary = Color(0xFF81C784),
            onTertiary = Color(0xFF0D3B12),
            background = Color(0xFF0A0A0A),
            onBackground = Color(0xFFF5F5F5),
            surface = Color(0xFF121212),
            onSurface = Color(0xFFF5F5F5),
            surfaceVariant = Color(0xFF1E1E1E),
            onSurfaceVariant = Color(0xFFE0E0E0),
            outline = Color(0xFF757575),
            error = Color(0xFFEF9A9A),
            onError = Color(0xFF7B0000),
            errorContainer = Color(0xFFB71C1C),
            onErrorContainer = Color(0xFFFFCDD2),
        ),
        gradients = AppGradientScheme(
            backgroundStart = Color(0xFF0A0A0A),
            backgroundMid = Color(0xFF0D1B2A),
            backgroundEnd = Color(0xFF0A0A0A),
            cardGradientStart = Color(0xFF1A237E),
            cardGradientEnd = Color(0xFF0D47A1),
            primaryGradientStart = Color(0xFF1565C0),
            primaryGradientEnd = Color(0xFF0A2F6B),
            accentGradientStart = Color(0xFFE65100),
            accentGradientEnd = Color(0xFFBF360C),
        )
    )

    val ForestGreen = AppTheme(
        id = "forest_green",
        displayName = "Forest",
        emoji = "🌿",
        isDark = false,
        colors = AppColorScheme(
            primary = Color(0xFF2E7D32),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFC8E6C9),
            onPrimaryContainer = Color(0xFF0D3B12),
            secondary = Color(0xFFFF8F00),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFFECB3),
            onSecondaryContainer = Color(0xFF6D4C00),
            tertiary = Color(0xFF1565C0),
            onTertiary = Color.White,
            background = Color(0xFFF1F8E9),
            onBackground = Color(0xFF1B2A1C),
            surface = Color.White,
            onSurface = Color(0xFF1B2A1C),
            surfaceVariant = Color(0xFFE8F5E9),
            onSurfaceVariant = Color(0xFF33691E),
            outline = Color(0xFFA5D6A7),
            error = Color(0xFFE53935),
            onError = Color.White,
            errorContainer = Color(0xFFFFCDD2),
            onErrorContainer = Color(0xFF7B0000),
        ),
        gradients = AppGradientScheme(
            backgroundStart = Color(0xFF0D1F0E),
            backgroundMid = Color(0xFF1B5E20),
            backgroundEnd = Color(0xFF2E7D32),
            cardGradientStart = Color(0xFF2E7D32),
            cardGradientEnd = Color(0xFF1B5E20),
            primaryGradientStart = Color(0xFF2E7D32),
            primaryGradientEnd = Color(0xFF1B5E20),
            accentGradientStart = Color(0xFFFF8F00),
            accentGradientEnd = Color(0xFF6D4C00),
        )
    )

    val SunriseOrange = AppTheme(
        id = "sunrise_orange",
        displayName = "Sunrise",
        emoji = "🌅",
        isDark = false,
        colors = AppColorScheme(
            primary = Color(0xFFE65100),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE0B2),
            onPrimaryContainer = Color(0xFF7B1F00),
            secondary = Color(0xFF6A1B9A),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE1BEE7),
            onSecondaryContainer = Color(0xFF38006B),
            tertiary = Color(0xFF1565C0),
            onTertiary = Color.White,
            background = Color(0xFFFFF8F0),
            onBackground = Color(0xFF2D1600),
            surface = Color.White,
            onSurface = Color(0xFF2D1600),
            surfaceVariant = Color(0xFFFFF3E0),
            onSurfaceVariant = Color(0xFF7B1F00),
            outline = Color(0xFFFFCC80),
            error = Color(0xFFE53935),
            onError = Color.White,
            errorContainer = Color(0xFFFFCDD2),
            onErrorContainer = Color(0xFF7B0000),
        ),
        gradients = AppGradientScheme(
            backgroundStart = Color(0xFF2D1600),
            backgroundMid = Color(0xFFBF360C),
            backgroundEnd = Color(0xFFE65100),
            cardGradientStart = Color(0xFFE65100),
            cardGradientEnd = Color(0xFF7B1F00),
            primaryGradientStart = Color(0xFFE65100),
            primaryGradientEnd = Color(0xFFBF360C),
            accentGradientStart = Color(0xFF6A1B9A),
            accentGradientEnd = Color(0xFF38006B),
        )
    )

    val PurpleGalaxy = AppTheme(
        id = "purple_galaxy",
        displayName = "Galaxy",
        emoji = "🌌",
        isDark = true,
        colors = AppColorScheme(
            primary = Color(0xFFCE93D8),
            onPrimary = Color(0xFF38006B),
            primaryContainer = Color(0xFF6A1B9A),
            onPrimaryContainer = Color(0xFFE1BEE7),
            secondary = Color(0xFF80DEEA),
            onSecondary = Color(0xFF00363B),
            secondaryContainer = Color(0xFF00838F),
            onSecondaryContainer = Color(0xFFE0F7FA),
            tertiary = Color(0xFFFFCC80),
            onTertiary = Color(0xFF4A2800),
            background = Color(0xFF0D0015),
            onBackground = Color(0xFFF3E5F5),
            surface = Color(0xFF150020),
            onSurface = Color(0xFFF3E5F5),
            surfaceVariant = Color(0xFF1E0030),
            onSurfaceVariant = Color(0xFFE1BEE7),
            outline = Color(0xFF7B1FA2),
            error = Color(0xFFEF9A9A),
            onError = Color(0xFF7B0000),
            errorContainer = Color(0xFFB71C1C),
            onErrorContainer = Color(0xFFFFCDD2),
        ),
        gradients = AppGradientScheme(
            backgroundStart = Color(0xFF0D0015),
            backgroundMid = Color(0xFF1A0030),
            backgroundEnd = Color(0xFF0D0015),
            cardGradientStart = Color(0xFF4A148C),
            cardGradientEnd = Color(0xFF6A1B9A),
            primaryGradientStart = Color(0xFF7B1FA2),
            primaryGradientEnd = Color(0xFF4A148C),
            accentGradientStart = Color(0xFF00838F),
            accentGradientEnd = Color(0xFF00363B),
        )
    )

    val all = listOf(OceanBlue, MidnightDark, ForestGreen, SunriseOrange, PurpleGalaxy)
    val default = OceanBlue
}
